export const Data = [
    {
        id: 1,
        month: "januari",
        ebook: 336,
        web: 1056,
    }, {
        id: 2,
        month: "februari",
        ebook: 921,
        web: 2178,
    }, {
        id: 3,
        month: "maret",
        ebook: 357,
        web: 982,
    }, {
        id: 4,
        month: "april",
        ebook: 11,
        web: 1538,
    }, {
        id: 5,
        month: "mei",
        ebook: 73,
        web: 897,
    }, {
        id: 6,
        month: "juni",
        ebook: 60,
        web: 1432,
    }, {
        id: 6,
        month: "juli",
        ebook: 40,
        web: 1670,
    }, {
        id: 6,
        month: "agustus",
        ebook: 44,
        web: 876,
    }, {
        id: 6,
        month: "september",
        ebook: 109,
        web: 1805,
    }, {
        id: 6,
        month: "oktober",
        ebook: 40,
        web: 1668,
    }, {
        id: 6,
        month: "november",
        ebook: 111,
        web: 1184,
    }, {
        id: 6,
        month: "desember",
        ebook: 231,
        web: 976,
    },
];